"""empty message

Revision ID: a8b30dfe5f6b
Revises: 
Create Date: 2020-03-15 01:05:29.514844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8b30dfe5f6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Type', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('parent_cat', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('image', sa.String(length=265), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_title'), 'category', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_title'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
